project:
  type: book
  output-dir: _book

book:
  title: "Introduction to R Workshop"
  author: "OIT Research Technology Services"
  reader-mode: false
  cover-image: images/r_logo.png
  sidebar:
    logo: images/logo_stack.svg
    pinned: true
  page-footer:
    right: <a href="http://creativecommons.org/licenses/by-sa/4.0/"><img src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>
  site-url: https://southernmethodistuniversity.github.io/intro-to-r/
  repo-url: https://github.com/SouthernMethodistUniversity/intro-to-r
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - setup.qmd
        - basics.qmd
    - part: objects.qmd
      chapters: 
        - data_types.qmd
        - data_structures.qmd
    - part: control.qmd
      chapters: 
        - functions.qmd
        - ifelse.qmd
        - loops.qmd
    - part: handson.qmd
      chapters: 
        - solutions.qmd
    - next_steps.qmd

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "SMU OIT Research Technology Services"
    callout-appearance: simple

editor: source