name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:latest  # Uses a prebuilt R environment with Quarto

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache R packages to speed up subsequent runs
      - name: Cache R Packages
        uses: actions/cache@v3
        with:
          path: /root/.local/share/R
          key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      # Install Quarto (if missing, which shouldn't be in rocker/verse)
      - name: Install Quarto (if needed)
        run: |
          if ! command -v quarto &> /dev/null; then
            wget https://quarto.org/download/latest/quarto-linux-amd64.deb
            sudo dpkg -i quarto-linux-amd64.deb
          fi

      # Install missing R packages
      - name: Install R Packages
        run: |
          Rscript -e 'needed <- c("rmarkdown", "tidyverse", "quarto"); \
                      installed <- rownames(installed.packages()); \
                      to_install <- setdiff(needed, installed); \
                      if (length(to_install) > 0) install.packages(to_install)'

      - name: Render Quarto Project
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './_book'